<a href="https://colab.research.google.com/github/Thitiphorn267-3/python_dataviz2023/blob/main/me.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

###Quiz 1
print มาก ที่มี ก 100ตัว

In [ ]:
'มา'+('ก' *100)

'มากกกกกกกกกกกกกกกกกกกกกกกกกกกกกกกกกกกกกกกกกกกกกกกกกกกกกกกกกกกกกกกกกกกกกกกกกกกกกกกกกกกกกกกกกกกกกกกกกกกก'

###QUIZ2
กำหนด list เป็นประโยคคำว่า "Department of Statistics, Faculty of Scine, Khon Kaen University, Thailand"

1.ตัดมาเฉพาะคำว่า Faculty of Scine
2.ตัดแบบเว้นทีละ 3 ตัวอักษร
3.ตัดคำว่า Khon Kaen University,Thailand ออกมาแล้วเขียนกลับหลัง

In [ ]:
list_Q2='Department of Statitics Faculty of Science, Khonkaen University, Thailand'

In [ ]:
list_Q2

'Department of Statitics Faculty of Science, Khonkaen University, Thailand'

In [ ]:
list_Q2[24:42] ##1

'Faculty of Science'

In [ ]:
list_Q2[::3] ##2

'DamtfticFuyfcn,hknnei,hld'

In [ ]:
list_Q2[43::-1]##3

' ,ecneicS fo ytlucaF scititatS fo tnemtrapeD'

##Quiz3
อยากได้รายการทั้งหมดที่ได้รับอนุมัติงบมากกว่า 1 ล้านบาท แต่ไม่เกิน 2 ล้าน

In [32]:
data2 = pd.read_csv('/content/drive/MyDrive/DataViz23Data/BKK.csv')
data2.head()

Budget_resource  Issue_No  Fiscal_year  Department_code        Department  \
0       งบประจำปี         0           62         11000000  สำนักการระบายน้ำ   
1       งบประจำปี         0           62         11000000  สำนักการระบายน้ำ   
2       งบประจำปี         0           62         11000000  สำนักการระบายน้ำ   
3       งบประจำปี         0           62         11000000  สำนักการระบายน้ำ   
4       งบประจำปี         0           62         11000000  สำนักการระบายน้ำ   

                                    Core_budget_code Expenditure_category  \
0  12-เงินสำรองจ่ายทั่วไป กรณีค่าใช้จ่ายต่างๆ เกี...              งบลงทุน   
1  12-เงินสำรองจ่ายทั่วไป กรณีค่าใช้จ่ายต่างๆ เกี...              งบลงทุน   
2  12-เงินสำรองจ่ายทั่วไป กรณีค่าใช้จ่ายต่างๆ เกี...              งบลงทุน   
3  12-เงินสำรองจ่ายทั่วไป กรณีค่าใช้จ่ายต่างๆ เกี...              งบลงทุน   
4  12-เงินสำรองจ่ายทั่วไป กรณีค่าใช้จ่ายต่างๆ เกี...              งบลงทุน   

                                           Item_name  Approved_buget  
0        ขุดลอกคลองบางกะปิจากคลองสามเสนถึงคลองแสนแสบ         1193000  
1  ขุดลอกคลองทรงกระเทียมจากคลองลาดพร้าวถึงถนนโชคช...         1100000  
2          ขุดลอกคลองเป้งจากคลองแสนแสบถึงซอยเจริญสุข         3075000  
3  ขุดลอกคลองลำพังพวยจากถนนศรีบูรพาถึงสถานีสูบน้ำ...         6240000  
4  ขุดลอกบึงรางเข้จากคลองพระยาราชมนตรีถึงถนนบางขุ...         2685000

In [33]:
data2[(data2['Approved_buget']>1000000)&(data2['Approved_buget']<=2000000)]

Budget_resource  Issue_No  Fiscal_year  Department_code  \
0         งบประจำปี         0           62         11000000   
1         งบประจำปี         0           62         11000000   
5         งบประจำปี         0           62         11000000   
22        งบประจำปี         0           63         11000000   
25        งบประจำปี         0           63         11000000   
..              ...       ...          ...              ...   
660     งบเพิ่มเติม         1           66         50350000   
662     งบเพิ่มเติม         1           66         50350000   
665     งบเพิ่มเติม         1           66         50350000   
666     งบเพิ่มเติม         1           66         50360000   
670     งบเพิ่มเติม         1           66         50360000   

             Department                                   Core_budget_code  \
0      สำนักการระบายน้ำ  12-เงินสำรองจ่ายทั่วไป กรณีค่าใช้จ่ายต่างๆ เกี...   
1      สำนักการระบายน้ำ  12-เงินสำรองจ่ายทั่วไป กรณีค่าใช้จ่ายต่างๆ เกี...   
5      สำนักการระบายน้ำ  12-เงินสำรองจ่ายทั่วไป กรณีค่าใช้จ่ายต่างๆ เกี...   
22     สำนักการระบายน้ำ  12-เงินสำรองจ่ายทั่วไป กรณีค่าใช้จ่ายต่างๆ เกี...   
25     สำนักการระบายน้ำ  12-เงินสำรองจ่ายทั่วไป กรณีค่าใช้จ่ายต่างๆ เกี...   
..                  ...                                                ...   
660  สำนักงานเขตบางพลัด                                                NaN   
662  สำนักงานเขตบางพลัด                                                NaN   
665  สำนักงานเขตบางพลัด                                                NaN   
666   สำนักงานเขตจอมทอง                                                NaN   
670   สำนักงานเขตจอมทอง                                                NaN   

    Expenditure_category                                          Item_name  \
0                งบลงทุน        ขุดลอกคลองบางกะปิจากคลองสามเสนถึงคลองแสนแสบ   
1                งบลงทุน  ขุดลอกคลองทรงกระเทียมจากคลองลาดพร้าวถึงถนนโชคช...   
5                งบลงทุน  ขุดลอกคลองราษฎร์สามัคคีจากคลองทวีวัฒนาถึงคลองม...   
22               งบลงทุน      ขุดลอกคลองนางหงษ์จากคลองแสนแสบถึงถนนบรรทัดทอง   
25               งบลงทุน  ขุดลอกคลองราษฎร์บูรณะจากแม่น้ำเจ้าพระยาถึงสวนธ...   
..                   ...                                                ...   
660              งบลงทุน                                 ขุดลอกคลองสะพานยาว   
662              งบลงทุน         ขุดลอกคลองบางรักและคูน้ำซอยจรัญสนิทวงศ์ 89   
665              งบลงทุน                           ขุดลอกคลองวัดน้อยนางหงษ์   
666              งบลงทุน  ขุดลอกคลองลัดบางสะแก (1),(2) จากคลองบางค้อและค...   
670              งบลงทุน  ขุดลอกลำกระโดงสาธารณประโยชน์แยกคลองต้นไทร (3),...   

     Approved_buget  
0           1193000  
1           1100000  
5           1207000  
22          1508000  
25          1975000  
..              ...  
660         1756000  
662         1859000  
665         1187000  
666         1581000  
670         1388000  

[132 rows x 9 columns]

## Quiz4
ตัดตาราง sep_df ให้เหลือเฉพาะ 15 column แรก และ ข้อมูล งบประจำ กับงบลงทุน

In [ ]:
sep_df = pd.read_excel('/content/drive/MyDrive/DataViz23Data/sep65.xlsx',header=8,skipfooter=26)
sep_df

รายการ      งบประมาณ  สำรองเงินมีหนี้  \
0  งบประมาณรายจ่ายประจำปี พ.ศ.2565           NaN              NaN   
1                           ภาพรวม  2.852539e+10     3.476005e+08   
2                            ประจำ  1.892013e+10     7.925745e+07   
3                            ลงทุน  9.605258e+09     2.683430e+08   

             PO      เบิกจ่าย  ร้อยละ\nเบิกจ่าย  เป้า\nหมาย Q4  */- เป้าหมาย  \
0           NaN           NaN               NaN            NaN           NaN   
1  1.190636e+09  2.700392e+10         94.666269           93.0      1.666269   
2  7.131600e+07  1.880196e+10         99.375405           98.0      1.375405   
3  1.119320e+09  8.201965e+09         85.390363           75.0     10.390363   

   การใช้จ่าย (PO+เบิกจ่าย)  ร้อยละ\nการใช้จ่าย  ...  ลำดับ\nใช้จ่าย  \
0                       NaN                 NaN  ...             NaN   
1              2.854216e+10          100.058786  ...            51.0   
2              1.895253e+10          100.171242  ...             NaN   
3              9.589628e+09           99.837275  ...            15.0   

   Unnamed: 15  รายการ.1    งบประมาณ.1    ผลเบิกจ่าย  ร้อยละเบิกจ่าย   \
0          NaN       NaN           NaN           NaN              NaN   
1          3.0    ภาพรวม  21663.922002  15260.448175        70.441761   
2          NaN     ประจำ  12452.794570  10580.839075        84.967587   
3         13.0     ลงทุน   9211.127432   4679.609100        50.803869   

  สูงกว่าเป้าหมาย     ผลการใช้จ่าย      ร้อยละ  สูงกว่าเป้าหมาย.1  
0       ไตรมาส 2   (PO + เบิกจ่าย)  การใช้จ่าย           ไตรมาส 2  
1       19.441761     18069.314644   83.407403          27.167403  
2       27.967587     10614.976114   85.241719          29.461719  
3       21.803869       7454.33853   80.927537          22.777537  

[4 rows x 24 columns]

In [ ]:
sep_df = sep_df.iloc[-2:,:15]
sep_df

In [ ]:
sep_df['เดือน-ปี'] = len(sep_df)*['sep-65']

In [ ]:
oct_df

รายการ     งบประมาณ  สำรองเงินมีหนี้          PO     เบิกจ่าย  \
2  ประจำ  6822.811789              NaN   12.706842  3984.779058   
3  ลงทุน  6180.211723              NaN  457.295806  1291.209026   

   ร้อยละ\nเบิกจ่าย  เป้า\nหมาย Q1  */- เป้าหมาย  การใช้จ่าย (PO+เบิกจ่าย)  \
2         58.403766           35.0     23.403766               3997.485900   
3         20.892634           19.0      1.892634               1748.504832   

   ร้อยละ\nการใช้จ่าย  เป้า\nหมาย Q1.1  */- เป้าหมาย.1  \
2           58.590007            35.33       23.260007   
3           28.291989            28.96       -0.668011   

   คงเหลือ\nหลังหักใช้จ่าย  ลำดับเบิกจ่าย  ลำดับ\nใช้จ่าย เดือน-ปี  
2              2825.325889            NaN             NaN   oct-65  
3              4431.706890            4.0             6.0   oct-65

In [ ]:
oct_df = pd.read_excel('/content/drive/MyDrive/DataViz23Data/Oct65.xlsx',header=9,skipfooter=27)
oct_df = oct_df.iloc[-2:,:15]
oct_df['เดือน-ปี'] = len(oct_df)*['oct-65']
oct_df

รายการ     งบประมาณ  สำรองเงินมีหนี้          PO     เบิกจ่าย  \
2  ประจำ  6822.811789              NaN   12.706842  3984.779058   
3  ลงทุน  6180.211723              NaN  457.295806  1291.209026   

   ร้อยละ\nเบิกจ่าย  เป้า\nหมาย Q1  */- เป้าหมาย  การใช้จ่าย (PO+เบิกจ่าย)  \
2         58.403766           35.0     23.403766               3997.485900   
3         20.892634           19.0      1.892634               1748.504832   

   ร้อยละ\nการใช้จ่าย  เป้า\nหมาย Q1.1  */- เป้าหมาย.1  \
2           58.590007            35.33       23.260007   
3           28.291989            28.96       -0.668011   

   คงเหลือ\nหลังหักใช้จ่าย  ลำดับเบิกจ่าย  ลำดับ\nใช้จ่าย เดือน-ปี  
2              2825.325889            NaN             NaN   oct-65  
3              4431.706890            4.0             6.0   oct-65

In [ ]:
oct_df = oct_df.iloc[-2:,:15]
oct_df['เดือน-ปี'] = len(oct_df)*['oct-65']

In [ ]:
oct_df = pd.read_excel('/content/drive/MyDrive/DataViz23Data/Oct65.xlsx',header=9,skipfooter=27)
oct_df = oct_df.iloc[-2:,:15]
oct_df['เดือน-ปี'] = len(oct_df)*['oct-65']

##HW1
คำนวณว่าช่วงเวลาต่อไปนี้ ห่างกันกี่ชั่วโมง กี่นาที กี่วินาที (print ออกมาให้สวยงาม)

12:30:15 - 13:41:07
09:11:50 - 21:30:15
19:25:30 - 03:10:15

In [ ]:
# 12:30:15 - 13:41:07
q1 = '12:30:15'
Q1 = q1.split(":")
hours1 = int(Q1[0])*3600
minutes1 = int(Q1[1])*60
seconds1 = int(Q1[2])
q2 = '13:41:07'
Q2 = q2.split(":")
hours2 = int(Q2[0])*3600
minutes2 = int(Q2[1])*60
seconds2 = int(Q2[2])
f1 =  hours1 + minutes1 + seconds1
f2 =  hours2 + minutes2 + seconds2
f3 = (f2-f1)
rh = int(f3/3600)
rm = int((f3%3600)/60)
rs = int(f3%60)
print(f' ช่วงเวลาจาก {q1} ถึง {q2} ห่างกัน {rh:,} ชั่วโมง {rm:,} นาที {rs:,} วินาที')

 ช่วงเวลาจาก 12:30:15 ถึง 13:41:07 ห่างกัน 1 ชั่วโมง 10 นาที 52 วินาที


In [ ]:
# 09:11:50 - 21:30:15
q1 = '09:11:50'
Q1 = q1.split(":")
hours1 = int(Q1[0])*3600
minutes1 = int(Q1[1])*60
seconds1 = int(Q1[2])
q2 = '21:30:15'
Q2 = q2.split(":")
hours2 = int(Q2[0])*3600
minutes2 = int(Q2[1])*60
seconds2 = int(Q2[2])
f1 =  hours1 + minutes1 + seconds1
f2 =  hours2 + minutes2 + seconds2
f3 = (f2-f1)
rh = int(f3/3600)
rm = int((f3%3600)/60)
rs = int(f3%60)
print(f' ช่วงเวลาจาก {q1} ถึง {q2} ห่างกัน {rh:,} ชั่วโมง {rm:,} นาที {rs:,} วินาที')

 ช่วงเวลาจาก 09:11:50 ถึง 21:30:15 ห่างกัน 12 ชั่วโมง 18 นาที 25 วินาที


In [ ]:
### แก้ไข
q5 = '03:10:15'
Q5 = q5.split(":")
hours5 = int(Q5[0])*3600
minutes5 = int(Q5[1])*60
seconds5 = int(Q5[2])
f5 =  hours5 + minutes5 + seconds5
print(f' {q5} แปลงเป็นวินาที ได้ {f5:,} วินาที')

q6 = '19:25:30'
Q6 = q6.split(":")
hours6 = int(Q6[0])*3600
minutes6 = int(Q6[1])*60
seconds6 = int(Q6[2])
f6 =  hours6 + minutes6 + seconds6
print(f' {q6} แปลงเป็นวินาที ได้ {f6:,} วินาที')

f7 = (f5+86400)-f6

hr = int(f7/3600)
mn = int((f7%3600)/60)
s = int(f7%60)
print(f' จาก {q5} ถึง {q6} ห่างกัน {hr:,} ชั่วโมง {mn:,} นาที {s:,} วินาที')

 03:10:15 แปลงเป็นวินาที ได้ 11,415 วินาที
 19:25:30 แปลงเป็นวินาที ได้ 69,930 วินาที
 จาก 03:10:15 ถึง 19:25:30 ห่างกัน 7 ชั่วโมง 44 นาที 45 วินาที


##HW2
สร้าง logo พรรคก้าวไกล

In [ ]:
import numpy as np # import เเล้วเปลี่ยนชื่อ จาก numpy เป็น np

In [ ]:
ส้ม = np.ones((21,16))
ส้ม[2:5,2:14] = 88
ส้ม[5:7,12:14] = 88
ส้ม[6:8,12:13] = 88
ส้ม[7:9,11:13] = 88
ส้ม[8:10,11:12] = 88
ส้ม[9:10,10:11] = 88
ส้ม[10:11,10:12] = 88
ส้ม[11:12,9:11] = 88
ส้ม[12:13,9:11] = 88
ส้ม[13:14,8:10] = 88
ส้ม[14:15,8:10] = 88
ส้ม[15:16,7:9] = 88
ส้ม[16:17,7:9] = 88
ส้ม[17:18,6:8] = 88
ส้ม[18:19,6:8] = 88

ส้ม[7,3:10] = 88
ส้ม[8,3:9] = 88
ส้ม[9,7:9] = 88
ส้ม[10,6:8] = 88
ส้ม[11,6:8] = 88
ส้ม[12,5:7] = 88
ส้ม[13,5:7] = 88
ส้ม[14,5] = 88

print(ส้ม)

[[ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  1. 88. 88. 88. 88. 88. 88. 88. 88. 88. 88. 88. 88.  1.  1.]
 [ 1.  1. 88. 88. 88. 88. 88. 88. 88. 88. 88. 88. 88. 88.  1.  1.]
 [ 1.  1. 88. 88. 88. 88. 88. 88. 88. 88. 88. 88. 88. 88.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1. 88. 88.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1. 88. 88.  1.  1.]
 [ 1.  1.  1. 88. 88. 88. 88. 88. 88. 88.  1. 88. 88.  1.  1.  1.]
 [ 1.  1.  1. 88. 88. 88. 88. 88. 88.  1.  1. 88. 88.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.  1. 88. 88.  1. 88. 88.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1. 88. 88.  1.  1. 88. 88.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1. 88. 88.  1. 88. 88.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1. 88. 88.  1.  1. 88. 88.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1. 88. 88.  1. 88. 88.  1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1. 88.  1.  1. 88. 88.  1.  1.  1.  1.  1. 

In [ ]:
def กก(x):
 ส้ม = x * np.ones((21,16))

 ส้ม[2:5,2:14] = 88
 ส้ม[5:7,12:14] = 88
 ส้ม[6:8,12:13] = 88
 ส้ม[7:9,11:13] = 88
 ส้ม[8:10,11:12] = 88
 ส้ม[9:10,10:11] = 88
 ส้ม[10:11,10:12] = 88
 ส้ม[11:12,9:11] = 88
 ส้ม[12:13,9:11] = 88
 ส้ม[13:14,8:10] = 88
 ส้ม[14:15,8:10] = 88
 ส้ม[15:16,7:9] = 88
 ส้ม[16:17,7:9] = 88
 ส้ม[17:18,6:8] = 88
 ส้ม[18:19,6:8] = 88

 ส้ม[7,3:10] = 88
 ส้ม[8,3:9] = 88
 ส้ม[9,7:9] = 88
 ส้ม[10,6:8] = 88
 ส้ม[11,6:8] = 88
 ส้ม[12,5:7] = 88
 ส้ม[13,5:7] = 88
 ส้ม[14,5] = 88



 print(ส้ม)

In [ ]:
กก(7)

[[ 7.  7.  7.  7.  7.  7.  7.  7.  7.  7.  7.  7.  7.  7.  7.  7.]
 [ 7.  7.  7.  7.  7.  7.  7.  7.  7.  7.  7.  7.  7.  7.  7.  7.]
 [ 7.  7. 88. 88. 88. 88. 88. 88. 88. 88. 88. 88. 88. 88.  7.  7.]
 [ 7.  7. 88. 88. 88. 88. 88. 88. 88. 88. 88. 88. 88. 88.  7.  7.]
 [ 7.  7. 88. 88. 88. 88. 88. 88. 88. 88. 88. 88. 88. 88.  7.  7.]
 [ 7.  7.  7.  7.  7.  7.  7.  7.  7.  7.  7.  7. 88. 88.  7.  7.]
 [ 7.  7.  7.  7.  7.  7.  7.  7.  7.  7.  7.  7. 88. 88.  7.  7.]
 [ 7.  7.  7. 88. 88. 88. 88. 88. 88. 88.  7. 88. 88.  7.  7.  7.]
 [ 7.  7.  7. 88. 88. 88. 88. 88. 88.  7.  7. 88. 88.  7.  7.  7.]
 [ 7.  7.  7.  7.  7.  7.  7. 88. 88.  7. 88. 88.  7.  7.  7.  7.]
 [ 7.  7.  7.  7.  7.  7. 88. 88.  7.  7. 88. 88.  7.  7.  7.  7.]
 [ 7.  7.  7.  7.  7.  7. 88. 88.  7. 88. 88.  7.  7.  7.  7.  7.]
 [ 7.  7.  7.  7.  7. 88. 88.  7.  7. 88. 88.  7.  7.  7.  7.  7.]
 [ 7.  7.  7.  7.  7. 88. 88.  7. 88. 88.  7.  7.  7.  7.  7.  7.]
 [ 7.  7.  7.  7.  7. 88.  7.  7. 88. 88.  7.  7.  7.  7.  7. 

## HW3

In [ ]:
import pandas as pd

In [ ]:
from google.colab import drive
drive.mount('/content/drive') # เชื่อมไดร์ฟ

Mounted at /content/drive


In [ ]:
data1 = pd.read_csv('/content/drive/MyDrive/DataViz23Data/BKK.csv')
data1.head()

Budget_resource  Issue_No  Fiscal_year  Department_code        Department  \
0       งบประจำปี         0           62         11000000  สำนักการระบายน้ำ   
1       งบประจำปี         0           62         11000000  สำนักการระบายน้ำ   
2       งบประจำปี         0           62         11000000  สำนักการระบายน้ำ   
3       งบประจำปี         0           62         11000000  สำนักการระบายน้ำ   
4       งบประจำปี         0           62         11000000  สำนักการระบายน้ำ   

                                    Core_budget_code Expenditure_category  \
0  12-เงินสำรองจ่ายทั่วไป กรณีค่าใช้จ่ายต่างๆ เกี...              งบลงทุน   
1  12-เงินสำรองจ่ายทั่วไป กรณีค่าใช้จ่ายต่างๆ เกี...              งบลงทุน   
2  12-เงินสำรองจ่ายทั่วไป กรณีค่าใช้จ่ายต่างๆ เกี...              งบลงทุน   
3  12-เงินสำรองจ่ายทั่วไป กรณีค่าใช้จ่ายต่างๆ เกี...              งบลงทุน   
4  12-เงินสำรองจ่ายทั่วไป กรณีค่าใช้จ่ายต่างๆ เกี...              งบลงทุน   

                                           Item_name  Approved_buget  
0        ขุดลอกคลองบางกะปิจากคลองสามเสนถึงคลองแสนแสบ         1193000  
1  ขุดลอกคลองทรงกระเทียมจากคลองลาดพร้าวถึงถนนโชคช...         1100000  
2          ขุดลอกคลองเป้งจากคลองแสนแสบถึงซอยเจริญสุข         3075000  
3  ขุดลอกคลองลำพังพวยจากถนนศรีบูรพาถึงสถานีสูบน้ำ...         6240000  
4  ขุดลอกบึงรางเข้จากคลองพระยาราชมนตรีถึงถนนบางขุ...         2685000


1.  รายการที่แพงและถูกที่สุดคือรายการไหน
2.  รายการขุดลอกคูคลองของ 'สำนักงานเขตคลองสานและสำนักงานเขตคลองสามวา'
3.  จากข้อ2 เขตไหนใช้งบประมาณเยอะกว่ากัน
4.  Core Budget ไหน (-เงินสำรองจ่ายทั่วไป กรณีค่าใช้จ่ายต่างๆเกี่ยวกับน้ำท่วม', '17-เงินสำรองจ่ายทั่วไป กรณีค่าใช้จ่ายเพื่อการพัฒนากรุงเทพมหานคร','28-เงินสำรองค่าใช้จ่าย ในการพัฒนาเขต') มีค่าเฉลี่ยงบประมาณที่ถูกอนุมัติสูงที่สุด



In [ ]:
data1

Budget_resource  Issue_No  Fiscal_year  Department_code  \
0         งบประจำปี         0           62         11000000   
1         งบประจำปี         0           62         11000000   
2         งบประจำปี         0           62         11000000   
3         งบประจำปี         0           62         11000000   
4         งบประจำปี         0           62         11000000   
..              ...       ...          ...              ...   
687     งบเพิ่มเติม         1           66         50460000   
688     งบเพิ่มเติม         1           66         50460000   
689     งบเพิ่มเติม         1           66         50460000   
690     งบเพิ่มเติม         1           66         50460000   
691     งบเพิ่มเติม         1           66         50500000   

               Department                                   Core_budget_code  \
0        สำนักการระบายน้ำ  12-เงินสำรองจ่ายทั่วไป กรณีค่าใช้จ่ายต่างๆ เกี...   
1        สำนักการระบายน้ำ  12-เงินสำรองจ่ายทั่วไป กรณีค่าใช้จ่ายต่างๆ เกี...   
2        สำนักการระบายน้ำ  12-เงินสำรองจ่ายทั่วไป กรณีค่าใช้จ่ายต่างๆ เกี...   
3        สำนักการระบายน้ำ  12-เงินสำรองจ่ายทั่วไป กรณีค่าใช้จ่ายต่างๆ เกี...   
4        สำนักการระบายน้ำ  12-เงินสำรองจ่ายทั่วไป กรณีค่าใช้จ่ายต่างๆ เกี...   
..                    ...                                                ...   
687  สำนักงานเขตคลองสามวา                                                NaN   
688  สำนักงานเขตคลองสามวา                                                NaN   
689  สำนักงานเขตคลองสามวา                                                NaN   
690  สำนักงานเขตคลองสามวา                                                NaN   
691     สำนักงานเขตบางบอน                                                NaN   

    Expenditure_category                                          Item_name  \
0                งบลงทุน        ขุดลอกคลองบางกะปิจากคลองสามเสนถึงคลองแสนแสบ   
1                งบลงทุน  ขุดลอกคลองทรงกระเทียมจากคลองลาดพร้าวถึงถนนโชคช...   
2                งบลงทุน          ขุดลอกคลองเป้งจากคลองแสนแสบถึงซอยเจริญสุข   
3                งบลงทุน  ขุดลอกคลองลำพังพวยจากถนนศรีบูรพาถึงสถานีสูบน้ำ...   
4                งบลงทุน  ขุดลอกบึงรางเข้จากคลองพระยาราชมนตรีถึงถนนบางขุ...   
..                   ...                                                ...   
687              งบลงทุน                                 ขุดลอกคลองผักกะเฉด   
688              งบลงทุน                            ขุดลอกคลองบึงทรายกองดิน   
689              งบลงทุน                                  ขุดลอกลำรางซาฟารี   
690              งบลงทุน                                ขุดลอกลำรางตาจันทร์   
691              งบลงทุน          ขุดลอกคลองบางบอนต่อจากของเดิมถึงคลองนายผล   

     Approved_buget  
0           1193000  
1           1100000  
2           3075000  
3           6240000  
4           2685000  
..              ...  
687         3686000  
688         2575000  
689          689000  
690          464000  
691         7578000  

[692 rows x 9 columns]

ข้อ 1

In [ ]:
data1.max()

<ipython-input-5-757cba64bfec>:1: FutureWarning: The default value of numeric_only in DataFrame.max is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  data1.max()


Budget_resource                                               งบเพิ่มเติม
Issue_No                                                                2
Fiscal_year                                                            66
Department_code                                                  50500000
Department                                            สำนักงานเขตห้วยขวาง
Expenditure_category                                              งบลงทุน
Item_name               ลอกดินเลนใต้สะพานท่อลอดถนนทางพิเศษเฉลิมมหานคร ...
Approved_buget                                                   28500000
dtype: object

In [ ]:
data1.min()

<ipython-input-6-f7a2de8a0b3a>:1: FutureWarning: The default value of numeric_only in DataFrame.min is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  data1.min()


Budget_resource                                                 งบประจำปี
Issue_No                                                                0
Fiscal_year                                                            62
Department_code                                                  11000000
Department                                               สำนักการระบายน้ำ
Expenditure_category                                              งบลงทุน
Item_name                ขุดลอกลำกระโดงสาธารณประโยชน์ข้างซอยพระรามที่ ...
Approved_buget                                                          0
dtype: object

In [ ]:
data1_max =data1['Approved_buget'].max()
data1_min = data1['Approved_buget'].min()
data1[(data1['Approved_buget'] == data1_max)|(data1['Approved_buget'] == data1_min)]

Budget_resource  Issue_No  Fiscal_year  Department_code  \
576     งบเพิ่มเติม         1           66         11000000   
612     งบเพิ่มเติม         1           66         50180000   
613     งบเพิ่มเติม         1           66         50180000   
631     งบเพิ่มเติม         1           66         50240000   

                 Department Core_budget_code Expenditure_category  \
576        สำนักการระบายน้ำ              NaN              งบลงทุน   
612       สำนักงานเขตธนบุรี              NaN              งบลงทุน   
613       สำนักงานเขตธนบุรี              NaN              งบลงทุน   
631  สำนักงานเขตราษฎร์บูรณะ              NaN              งบลงทุน   

                                             Item_name  Approved_buget  
576  ขุดลอกคลองพระยาสุเรนทร์ จากคลองหกวาถึงคลองบางช...        28500000  
612  ขุดลอกลำกระโดงอำนวยสุข จากคลองบางกอกใหญ่ถึงสุด...               0  
613  ขุดลอกคลองแยกวัดประดู่ จากคลองบางกอกใหญ่ถึงคลอ...               0  
631   ขุดลอกคลองต้นโศกจากคลองราษฎร์บูรณะถึงคลองแจงร้อน               0

ข้อ 2

In [ ]:
data1[(data1['Department'] == 'สำนักงานเขตคลองสาน') | (data1['Department'] == 'สำนักงานเขตคลองสามวา')]

Budget_resource  Issue_No  Fiscal_year  Department_code  \
57        งบประจำปี         0           62         50170000   
58        งบประจำปี         0           62         50170000   
59        งบประจำปี         0           62         50170000   
122       งบประจำปี         0           63         50170000   
123       งบประจำปี         0           63         50170000   
212       งบประจำปี         0           64         50170000   
213       งบประจำปี         0           64         50170000   
214       งบประจำปี         0           64         50170000   
215       งบประจำปี         0           64         50170000   
252       งบประจำปี         0           64         50460000   
253       งบประจำปี         0           64         50460000   
271       งบประจำปี         0           65         50170000   
400     งบเพิ่มเติม         1           65         50460000   
401     งบเพิ่มเติม         1           65         50460000   
402     งบเพิ่มเติม         1           65         50460000   
403     งบเพิ่มเติม         1           65         50460000   
404     งบเพิ่มเติม         1           65         50460000   
441       งบประจำปี         0           66         50170000   
442       งบประจำปี         0           66         50170000   
443       งบประจำปี         0           66         50170000   
681     งบเพิ่มเติม         1           66         50460000   
682     งบเพิ่มเติม         1           66         50460000   
683     งบเพิ่มเติม         1           66         50460000   
684     งบเพิ่มเติม         1           66         50460000   
685     งบเพิ่มเติม         1           66         50460000   
686     งบเพิ่มเติม         1           66         50460000   
687     งบเพิ่มเติม         1           66         50460000   
688     งบเพิ่มเติม         1           66         50460000   
689     งบเพิ่มเติม         1           66         50460000   
690     งบเพิ่มเติม         1           66         50460000   

               Department Core_budget_code Expenditure_category  \
57     สำนักงานเขตคลองสาน                -              งบลงทุน   
58     สำนักงานเขตคลองสาน                -              งบลงทุน   
59     สำนักงานเขตคลองสาน                -              งบลงทุน   
122    สำนักงานเขตคลองสาน                -              งบลงทุน   
123    สำนักงานเขตคลองสาน                -              งบลงทุน   
212    สำนักงานเขตคลองสาน                -              งบลงทุน   
213    สำนักงานเขตคลองสาน                -              งบลงทุน   
214    สำนักงานเขตคลองสาน                -              งบลงทุน   
215    สำนักงานเขตคลองสาน                -              งบลงทุน   
252  สำนักงานเขตคลองสามวา                -              งบลงทุน   
253  สำนักงานเขตคลองสามวา                -              งบลงทุน   
271    สำนักงานเขตคลองสาน              NaN              งบลงทุน   
400  สำนักงานเขตคลองสามวา              NaN              งบลงทุน   
401  สำนักงานเขตคลองสามวา              NaN              งบลงทุน   
402  สำนักงานเขตคลองสามวา              NaN              งบลงทุน   
403  สำนักงานเขตคลองสามวา              NaN              งบลงทุน   
404  สำนักงานเขตคลองสามวา              NaN              งบลงทุน   
441    สำนักงานเขตคลองสาน              NaN              งบลงทุน   
442    สำนักงานเขตคลองสาน              NaN              งบลงทุน   
443    สำนักงานเขตคลองสาน              NaN              งบลงทุน   
681  สำนักงานเขตคลองสามวา              NaN              งบลงทุน   
682  สำนักงานเขตคลองสามวา              NaN              งบลงทุน   
683  สำนักงานเขตคลองสามวา              NaN              งบลงทุน   
684  สำนักงานเขตคลองสามวา              NaN              งบลงทุน   
685  สำนักงานเขตคลองสามวา              NaN              งบลงทุน   
686  สำนักงานเขตคลองสามวา              NaN              งบลงทุน   
687  สำนักงานเขตคลองสามวา              NaN              งบลงทุน   
688  สำนักงานเขตคลองสามวา              NaN              งบลงทุน   
689  สำนักงานเขตคลองสามวา              NaN              งบลงทุน   
690  สำนักงานเขตคลองสามวา              N

ข้อ 3

In [ ]:
data_2 = data1[(data1['Department'] == 'สำนักงานเขตคลองสาน')]
data_3 = data_2['Approved_buget'].sum()
print('สำนักงานเขตคลองสาน ใช้งบประมาณไปทั้งหมด', data_3) ,
data_4 = data1[(data1['Department'] == 'สำนักงานเขตคลองสามวา')]
data_5 = data_4['Approved_buget'].sum()
print('สำนักงานเขตคลองสามวา ใช้งบประมาณไปทั้งหมด', data_5)


สำนักงานเขตคลองสาน ใช้งบประมาณไปทั้งหมด 6895000
สำนักงานเขตคลองสามวา ใช้งบประมาณไปทั้งหมด 51378800


In [ ]:
if (data_3 < data_5):
   print('สำนักงานเขตคลองสานใช้งบประมาณมากกว่า')
elif (data_3 > data_5):
   print('สำนักงานเขตคลองสามวาใช้งบประมาณมากว่า')

สำนักงานเขตคลองสานใช้งบประมาณมากกว่า


ข้อ 4

In [ ]:
Core_data1 = data1.dropna()
CoreBudget_data1 = Core_data1[Core_data1['Core_budget_code'] != '-']
CoreBudget_data1_12 =CoreBudget_data1[CoreBudget_data1['Core_budget_code'] == '12-เงินสำรองจ่ายทั่วไป กรณีค่าใช้จ่ายต่างๆ เกี่ยวกับน้ำท่วม']
CoreBudget_data1_28 =CoreBudget_data1[CoreBudget_data1['Core_budget_code'] == '28-เงินสำรองค่าใช้จ่าย ในการพัฒนาเขต']
CoreBudget_data1_17 =CoreBudget_data1[CoreBudget_data1['Core_budget_code'] == '17-เงินสำรองจ่ายทั่วไป กรณีค่าใช้จ่ายเพื่อการพัฒนากรุงเทพมหานคร']
CoreBudget = []
x=set(CoreBudget_data1['Core_budget_code'])
for n in x:
  CoreBudget.append(n)
CoreBudget_data1_12_MEAN =CoreBudget_data1_12['Approved_buget'].mean()
CoreBudget_data1_17_MEAN =CoreBudget_data1_17['Approved_buget'].mean()
CoreBudget_data1_28_MEAN =CoreBudget_data1_28['Approved_buget'].mean()


In [ ]:
if (CoreBudget_data1_12_MEAN > CoreBudget_data1_17_MEAN ) & (CoreBudget_data1_12_MEAN > CoreBudget_data1_28_MEAN ):
  print(f'รายการนี้ {CoreBudget[2]} มีค่าเฉลี่ยงบประมาณที่ถูกอนุมัติสูงที่สุด {CoreBudget_data1_12_MEAN}')
elif (CoreBudget_data1_17_MEAN > CoreBudget_data1_12_MEAN ) & (CoreBudget_data1_17_MEAN > CoreBudget_data1_28_MEAN ):
  print(f'รายการนี้ {CoreBudget[0]} มีค่าเฉลี่ยงบประมาณที่ถูกอนุมัติสูงที่สุด {CoreBudget_data1_17_MEAN}')
elif (CoreBudget_data1_28_MEAN > CoreBudget_data1_12_MEAN ) & (CoreBudget_data1_28_MEAN > CoreBudget_data1_17_MEAN ):
  print(f'รายการนี้ {CoreBudget[1]} มีค่าเฉลี่ยงบประมาณที่ถูกอนุมัติสูงที่สุด {CoreBudget_data1_28_MEAN}')

รายการนี้ 17-เงินสำรองจ่ายทั่วไป กรณีค่าใช้จ่ายเพื่อการพัฒนากรุงเทพมหานคร มีค่าเฉลี่ยงบประมาณที่ถูกอนุมัติสูงที่สุด 1837500.0


### นำข้อมูลเข้า Pandas101
ข้อมูล excel

In [ ]:
import pandas as pd
import os

In [ ]:
from google.colab import drive # เชื่อมบัญชีกับ google drive
drive.mount('/content/drive') # เช็คว่าเชื่อมติดหรือไม่

In [ ]:
sep_df = pd.read_excel('/content/drive/MyDrive/DataViz23Data/sep65.xlsx',header=8,skipfooter=26)
sep_df

รายการ      งบประมาณ  สำรองเงินมีหนี้  \
0  งบประมาณรายจ่ายประจำปี พ.ศ.2565           NaN              NaN   
1                           ภาพรวม  2.852539e+10     3.476005e+08   
2                            ประจำ  1.892013e+10     7.925745e+07   
3                            ลงทุน  9.605258e+09     2.683430e+08   

             PO      เบิกจ่าย  ร้อยละ\nเบิกจ่าย  เป้า\nหมาย Q4  */- เป้าหมาย  \
0           NaN           NaN               NaN            NaN           NaN   
1  1.190636e+09  2.700392e+10         94.666269           93.0      1.666269   
2  7.131600e+07  1.880196e+10         99.375405           98.0      1.375405   
3  1.119320e+09  8.201965e+09         85.390363           75.0     10.390363   

   การใช้จ่าย (PO+เบิกจ่าย)  ร้อยละ\nการใช้จ่าย  ...  ลำดับ\nใช้จ่าย  \
0                       NaN                 NaN  ...             NaN   
1              2.854216e+10          100.058786  ...            51.0   
2              1.895253e+10          100.171242  ...             NaN   
3              9.589628e+09           99.837275  ...            15.0   

   Unnamed: 15  รายการ.1    งบประมาณ.1    ผลเบิกจ่าย  ร้อยละเบิกจ่าย   \
0          NaN       NaN           NaN           NaN              NaN   
1          3.0    ภาพรวม  21663.922002  15260.448175        70.441761   
2          NaN     ประจำ  12452.794570  10580.839075        84.967587   
3         13.0     ลงทุน   9211.127432   4679.609100        50.803869   

  สูงกว่าเป้าหมาย     ผลการใช้จ่าย      ร้อยละ  สูงกว่าเป้าหมาย.1  
0       ไตรมาส 2   (PO + เบิกจ่าย)  การใช้จ่าย           ไตรมาส 2  
1       19.441761     18069.314644   83.407403          27.167403  
2       27.967587     10614.976114   85.241719          29.461719  
3       21.803869       7454.33853   80.927537          22.777537  

[4 rows x 24 columns]

In [ ]:
oct_df = pd.read_excel('/content/drive/MyDrive/DataViz23Data/Oct65.xlsx',header=9,skipfooter=27)
oct_df = oct_df.iloc[-2:,:15]
oct_df['เดือน-ปี'] = len(oct_df)*['oct-65']
oct_df

รายการ     งบประมาณ  สำรองเงินมีหนี้          PO     เบิกจ่าย  \
2  ประจำ  6822.811789              NaN   12.706842  3984.779058   
3  ลงทุน  6180.211723              NaN  457.295806  1291.209026   

   ร้อยละ\nเบิกจ่าย  เป้า\nหมาย Q1  */- เป้าหมาย  การใช้จ่าย (PO+เบิกจ่าย)  \
2         58.403766           35.0     23.403766               3997.485900   
3         20.892634           19.0      1.892634               1748.504832   

   ร้อยละ\nการใช้จ่าย  เป้า\nหมาย Q1.1  */- เป้าหมาย.1  \
2           58.590007            35.33       23.260007   
3           28.291989            28.96       -0.668011   

   คงเหลือ\nหลังหักใช้จ่าย  ลำดับเบิกจ่าย  ลำดับ\nใช้จ่าย เดือน-ปี  
2              2825.325889            NaN             NaN   oct-65  
3              4431.706890            4.0             6.0   oct-65

In [ ]:
oct_df = pd.read_excel('/content/drive/MyDrive/DataViz23Data/Oct65.xlsx',header=9,skipfooter=27)
oct_df = oct_df.iloc[-2:,:15]
oct_df['เดือน-ปี'] = len(oct_df)*['oct-65']

In [ ]:
sep_oct_df = pd.concat([sep_df,oct_df]) # ต่อตารางแกน Y
sep_oct_df

รายการ      งบประมาณ  สำรองเงินมีหนี้  \
0  งบประมาณรายจ่ายประจำปี พ.ศ.2565           NaN              NaN   
1                           ภาพรวม  2.852539e+10     3.476005e+08   
2                            ประจำ  1.892013e+10     7.925745e+07   
3                            ลงทุน  9.605258e+09     2.683430e+08   
2                            ประจำ  6.822812e+03              NaN   
3                            ลงทุน  6.180212e+03              NaN   

             PO      เบิกจ่าย  ร้อยละ\nเบิกจ่าย  เป้า\nหมาย Q4  */- เป้าหมาย  \
0           NaN           NaN               NaN            NaN           NaN   
1  1.190636e+09  2.700392e+10         94.666269           93.0      1.666269   
2  7.131600e+07  1.880196e+10         99.375405           98.0      1.375405   
3  1.119320e+09  8.201965e+09         85.390363           75.0     10.390363   
2  1.270684e+01  3.984779e+03         58.403766            NaN     23.403766   
3  4.572958e+02  1.291209e+03         20.892634            NaN      1.892634   

   การใช้จ่าย (PO+เบิกจ่าย)  ร้อยละ\nการใช้จ่าย  ...    งบประมาณ.1  \
0                       NaN                 NaN  ...           NaN   
1              2.854216e+10          100.058786  ...  21663.922002   
2              1.895253e+10          100.171242  ...  12452.794570   
3              9.589628e+09           99.837275  ...   9211.127432   
2              3.997486e+03           58.590007  ...           NaN   
3              1.748505e+03           28.291989  ...           NaN   

     ผลเบิกจ่าย  ร้อยละเบิกจ่าย   สูงกว่าเป้าหมาย     ผลการใช้จ่าย  \
0           NaN              NaN        ไตรมาส 2   (PO + เบิกจ่าย)   
1  15260.448175        70.441761        19.441761     18069.314644   
2  10580.839075        84.967587        27.967587     10614.976114   
3   4679.609100        50.803869        21.803869       7454.33853   
2           NaN              NaN              NaN              NaN   
3           NaN              NaN              NaN              NaN   

       ร้อยละ สูงกว่าเป้าหมาย.1  เป้า\nหมาย Q1  เป้า\nหมาย Q1.1  เดือน-ปี  
0  การใช้จ่าย          ไตรมาส 2            NaN              NaN       NaN  
1   83.407403         27.167403            NaN              NaN       NaN  
2   85.241719         29.461719            NaN              NaN       NaN  
3   80.927537         22.777537            NaN              NaN       NaN  
2         NaN               NaN           35.0            35.33    oct-65  
3         NaN               NaN           19.0            28.96    oct-65  

[6 rows x 27 columns]

## HW4

จากตาราง sep_oct_df

1. งบประมาณประจำหรืองบประมาณลงทุน สูงกว่ากัน
2. งบรวม เดือน Oct หรือ sep อันไหนมากกว่ากัน
3. แก้ค่า missing พร้อมทั้งให้เหตุผล
4. เดือนไหนเบิกจ่ายรวมมากกว่ากัน (การใช้จ่าย (PO+เบิกจ่าย))




`1. งบประมาณประจำหรืองบประมาณลงทุน สูงกว่ากัน`

In [ ]:
R_65 = sep_oct_df[sep_oct_df['รายการ']=='ประจำ']
L_65_N = sep_oct_df[sep_oct_df['รายการ']=='ลงทุน']
a=R_65['งบประมาณ'].sum()
b=L_65['งบประมาณ'].sum()
NG =[]
for x in set(sep_oct_df['รายการ']):
  NG.append(x)
NG
if a > b :
  print (f'งบที่สูงกว่าคืองบ{NG[0]} ซึ่งมากกว่างบ{NG[1]} เป็นเงินจำนวน {int(a-b):,} บาท')
elif a < b:
  print (f'งบที่สูงกว่าคืองบ{NG[1]} ซึ่งมากกว่างบ{NG[0]} เป็นเงินจำนวน {int(b-a):,} บาท')

2. งบรวม เดือน Oct หรือ sep อันไหนมากกว่ากัน

In [ ]:
R_65=sep_oct_df[sep_oct_df['เดือน-ปี']=='sep-65']
I_65=sep_oct_df[sep_oct_df['เดือน-ปี']=='oct-65']
a = R_65['งบประมาณ'].sum()
b = I_65['งบประมาณ'].sum()
NG =[]
for x in set(sep_oct_df['เดือน-ปี']):
  NG.append(x)
NG
if a > b :
   print(f'เดือนที่สูงกว่าคือเดือน{NG[0]} ซึ่งมากกว่าเดือน{NG[1]} เป็นเงินจำนวน {int(a-b):,} บาท')
elif a < b:
   print(f'เดือนที่สูงกว่าคือเดือน{NG[1]} ซึ่งมากกว่าเดือน{NG[0]} เป็นเงินจำนวน {int(b-a):,} บาท')

เดือนที่สูงกว่าคือเดือนoct-65 ซึ่งมากกว่าเดือนsep-65 เป็นเงินจำนวน 28,525,376,384 บาท


3.เเก้ค่า missing พร้อมทั้งให้เหตุผล

In [ ]:
newdf = sep_oct_df.fillna('-')
print ('เหตุผลที่เปลี่ยนค่า Nan เป็น - เพราะ')
print ('-หากใช้ .dropna จะทำให้rowทั้งหมดหายไปเนื่องจากทุก row มีค่า Nanหมด')
print ('-ในเดือนกันยายนไม่มีเป้าหมาย Q1 เเต่ในทางกลับกัน เดือนตุลาคมก็ไม่มีเป้าหมาย Q4 เช่นกัน')
print ('ในเดือนตุลาคมก็ไม่มีสำรองเงินมีหนี้ เเละ เงินประจำจะไม่มีลำดับเบิก/ใช้จ่าย')
print ('-ค่าที่เปลี่ยนนั้นเป็นข้อมูลเชิงคุณภาพที่หากใส่ตัวเลขเข้าไปก็สามารถทำให้เกิดความเข้าใจผิดได้ ดังนั้นเพื่อไม่ให้ความเข้าใจคาดเคลื่อนจึงใช้เป็น "-" เเทน ')
print ('')
print ('ตารางที่มีการเเก้ไขค่า missing เเล้ว')
newdf


เหตุผลที่เปลี่ยนค่า Nan เป็น - เพราะ
-หากใช้ .dropna จะทำให้rowทั้งหมดหายไปเนื่องจากทุก row มีค่า Nanหมด
-ในเดือนกันยายนไม่มีเป้าหมาย Q1 เเต่ในทางกลับกัน เดือนตุลาคมก็ไม่มีเป้าหมาย Q4 เช่นกัน
ในเดือนตุลาคมก็ไม่มีสำรองเงินมีหนี้ เเละ เงินประจำจะไม่มีลำดับเบิก/ใช้จ่าย
-ค่าที่เปลี่ยนนั้นเป็นข้อมูลเชิงคุณภาพที่หากใส่ตัวเลขเข้าไปก็สามารถทำให้เกิดความเข้าใจผิดได้ ดังนั้นเพื่อไม่ให้ความเข้าใจคาดเคลื่อนจึงใช้เป็น "-" เเทน 

ตารางที่มีการเเก้ไขค่า missing เเล้ว


รายการ     งบประมาณ  \
28  ที่มา : ระบบการบริหารการเงินการคลังภาครัฐแบบอิ...            -   
29                           ข้อมูล ณ 30 กันยายน 2565            -   
2                                               ประจำ  6822.811789   
3                                               ลงทุน  6180.211723   

   สำรองเงินมีหนี้          PO     เบิกจ่าย ร้อยละ\nเบิกจ่าย เป้า\nหมาย Q4  \
28               -           -            -                -             -   
29               -           -            -                -             -   
2                -   12.706842  3984.779058        58.403766             -   
3                -  457.295806  1291.209026        20.892634             -   

   */- เป้าหมาย การใช้จ่าย (PO+เบิกจ่าย) ร้อยละ\nการใช้จ่าย เป้า\nหมาย Q4.1  \
28            -                        -                  -               -   
29            -                        -                  -               -   
2     23.403766                3997.4859          58.590007               -   
3      1.892634              1748.504832          28.291989               -   

   */- เป้าหมาย.1 คงเหลือ\nหลังหักใช้จ่าย ลำดับเบิกจ่าย ลำดับ\nใช้จ่าย  \
28              -                       -             -              -   
29              -                       -             -              -   
2       23.260007             2825.325889             -              -   
3       -0.668011              4431.70689           4.0            6.0   

   เดือน-ปี เป้า\nหมาย Q1 เป้า\nหมาย Q1.1  
28   sep-65             -               -  
29   sep-65             -               -  
2    oct-65          35.0           35.33  
3    oct-65          19.0           28.96

4.เดือนไหนเบิกจ่ายรวมมากกว่ากัน (การใช้จ่าย (PO+เบิกจ่าย))

In [ ]:
R_65=sep_oct_df[sep_oct_df['เดือน-ปี']=='sep-65']
L_65=sep_oct_df[sep_oct_df['เดือน-ปี']=='oct-65']
a=R_65['การใช้จ่าย (PO+เบิกจ่าย)'].sum()
b=L_65['การใช้จ่าย (PO+เบิกจ่าย)'].sum()
NG =[]
for x in set(sep_oct_df['เดือน-ปี']):
  NG.append(x)
NG
if a > b :
  print (f'เดือนที่สูงกว่าคือเดือน{NG[0]}  เป็นเงินจำนวน {int(a):,} บาท')
elif a < b:
  print (f'เดือนที่สูงกว่าคือเดือน{NG[1]}  เป็นเงินจำนวน {int(b):,} บาท')

เดือนที่สูงกว่าคือเดือนoct-65  เป็นเงินจำนวน 28,542,158,434 บาท


### นำข้อมูลเข้า Pandas 102
ข้อมูล csv

In [35]:
import pandas as pd
import os

In [37]:
from google.colab import drive # เชื่อมบัญชีกับ google drive
drive.mount('/content/drive') # เช็คว่าเชื่อมติดหรือไม่

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [38]:
project_df = pd.read_csv('/content/drive/MyDrive/DataViz23Data/opendata_project-2.csv')
project_df.head()

row_number                project_id                     name_en  \
0     20809.0  5ec3409884c1860019f3298d    Baan Laksiri Surin-Korco   
1      4268.0             project_15905              Liberty Park 2   
2      5849.0  62b2b082cb0d2c0014be01a6  Pleno Paholyothin-Saimai 2   
3     21762.0              project_6010              Baan Thara Rin   
4     10751.0             project_11312             The Forest Hill   

                      name_th propertytype_id propertytype_name_en  \
0  บ้านหลักศิริ สุรินทร์-คอโค               3             Townhome   
1          ลิเบอร์ตี้ พาร์ค 2               2                Condo   
2    พลีโน่ พหลโยธิน-สายไหม 2               3             Townhome   
3              บ้านธารารินทร์               1       Detached House   
4          เดอะ ฟอเรสต์ ฮิลล์               1       Detached House   

  propertytype_name_th  price_min     developer_id  \
0             ทาวน์โฮม  1490000.0   developer_7326   
1                คอนโด  6500000.0  developer_10510   
2             ทาวน์โฮม  2790000.0   developer_1760   
3                 บ้าน  3100000.0  developer_10510   
4                 บ้าน  2450000.0   developer_7313   

                developer_name_en  ... facility_park  facility_playground  \
0  LAK SIRI REAL ESTATE CO., LTD.  ...           NaN                  NaN   
1                             NaN  ...           0.0                  0.0   
2     AP (THAILAND) PUB CO., LTD.  ...           1.0                  NaN   
3                             NaN  ...           NaN                  NaN   
4     Cholsiri Property Co., Ltd.  ...           1.0                  NaN   

   facility_pool facility_security         date_created          date_finish  \
0            1.0               1.0  2020-05-19 09:12:40                  NaN   
1            1.0               1.0  2019-06-28 16:06:45  1998-12-31 07:00:00   
2            1.0               1.0  2022-06-22 13:02:42  2024-01-01 07:00:00   
3            NaN               NaN  2017-04-19 14:41:10                  NaN   
4            1.0               1.0  2017-10-30 14:10:50  2018-12-31 07:00:00   

          date_updated  source  \
0  2020-12-04 10:33:10  baania   
1  2020-12-04 10:39:27  baania   
2  2023-03-20 15:00:04  baania   
3  2022-11-07 12:30:02  baania   
4  2022-08-15 16:00:05  baania   

                                         url_project         day  
0  https://baania.com/th/project/บ้านหลักศิริ-สุร...  2023-06-11  
1  https://baania.com/th/project/ลิเบอร์ตี้-พาร์ค...  2023-06-11  
2  https://baania.com/th/project/พลีโน่-พหลโยธิน-...  2023-06-11  
3  https://baania.com/th/project/บ้านธารารินทร์-p...  2023-06-11  
4  https://baania.com/th/project/เดอะ-ฟอเรสต์-ฮิล...  2023-06-11  

[5 rows x 46 columns]

In [40]:
unit_df = pd.read_csv('/content/drive/MyDrive/DataViz23Data/opendata_unittype-2.csv')
unit_df.head()

row_number               unittype_id                project_id  \
0       37586            unittype_35602             project_15270   
1        9427             unittype_4487              project_1476   
2       12994            unittype_37624             project_16674   
3       19073  62286afcc74d880014871357  622861f7aae18f00134066d6   
4       10907             unittype_8344              project_2821   

               name_th  propertytype_id propertytype_name_en  \
0               Studio                2                Condo   
1              ภัทรสิน                3             Townhome   
2               Type B                3             Townhome   
3      ทาวน์โฮมสองชั้น                3             Townhome   
4  2 Bedroom (ขายแล้ว)                2                Condo   

  propertytype_name_th  area_total_min_wa  area_usable_min  price_min  ...  \
0                คอนโด                NaN             30.0  3700000.0  ...   
1             ทาวน์โฮม                NaN              NaN  2000000.0  ...   
2             ทาวน์โฮม               24.0             96.0        NaN  ...   
3             ทาวน์โฮม                NaN              NaN  1000000.0  ...   
4                คอนโด                NaN             48.0  4200000.0  ...   

   count_room_kitchen  count_room_living  count_room_maid  count_room_storage  \
0                 NaN                NaN              NaN                 NaN   
1                 NaN                NaN              NaN                 NaN   
2                 NaN                NaN              NaN                 NaN   
3                 1.0                NaN              NaN                 NaN   
4                 1.0                1.0              NaN                 NaN   

   count_room_utility         date_created         date_updated  source  \
0                 NaN  2021-11-12 13:22:56  2020-10-14 20:21:01  baania   
1                 NaN  2021-11-12 13:20:17  2020-10-14 00:53:00  baania   
2                 NaN  2022-09-09 15:30:02  2022-09-09 15:03:18  baania   
3                 NaN  2022-03-09 16:30:04  2022-03-09 16:17:44  baania   
4                 NaN  2021-11-12 13:24:53  2020-10-16 16:46:17  baania   

                                        url_unittype         day  
0  https://baania.com/th/project/ไลฟ์-แอท-รัชดา-ส...  2023-06-11  
1  https://baania.com/th/project/บ้านสวนทรัพย์ธาน...  2023-06-11  
2  https://baania.com/th/project/สกายไลน์-อมตะ-16...  2023-06-11  
3  https://baania.com/th/project/รุ่งเรืองทรัพย์ว...  2023-06-11  
4  https://baania.com/th/project/เดอะ-เทมโป-แกรนด...  2023-06-11  

[5 rows x 28 columns]

In [42]:
project_df = project_df.drop_duplicates(subset='project_id')
unit_df['province_en'] = unit_df['project_id'].map(project_df.set_index('project_id')['province_name_en']) # ตารางรองคีย์ต้องไม่ซ้ำกัน

In [44]:
unit_df

row_number               unittype_id                project_id  \
0           37586            unittype_35602             project_15270   
1            9427             unittype_4487              project_1476   
2           12994            unittype_37624             project_16674   
3           19073  62286afcc74d880014871357  622861f7aae18f00134066d6   
4           10907             unittype_8344              project_2821   
...           ...                       ...                       ...   
43369        9507             unittype_5086              project_1635   
43370       23721            unittype_15644              project_6109   
43371       31551            unittype_21385              project_8392   
43372       29837            unittype_26243             project_10566   
43373        9465            unittype_35686             project_15298   

                          name_th  propertytype_id propertytype_name_en  \
0                          Studio                2                Condo   
1                         ภัทรสิน                3             Townhome   
2                          Type B                3             Townhome   
3                 ทาวน์โฮมสองชั้น                3             Townhome   
4             2 Bedroom (ขายแล้ว)                2                Condo   
...                           ...              ...                  ...   
43369         บ้านเดี่ยวชั้นเดียว                1       Detached House   
43370           บ้านเดี่ยวสองชั้น                1       Detached House   
43371  อาคารพาณิชย์สี่ชั้น type B                4           Commercial   
43372             ทาวน์โฮมสามชั้น                3             Townhome   
43373                   2 Bedroom                2                Condo   

      propertytype_name_th  area_total_min_wa  area_usable_min   price_min  \
0                    คอนโด                NaN             30.0   3700000.0   
1                 ทาวน์โฮม                NaN              NaN   2000000.0   
2                 ทาวน์โฮม               24.0             96.0         NaN   
3                 ทาวน์โฮม                NaN              NaN   1000000.0   
4                    คอนโด                NaN             48.0   4200000.0   
...                    ...                ...              ...         ...   
43369                 บ้าน                NaN              NaN    880000.0   
43370                 บ้าน               45.0            140.0   2400000.0   
43371         อาคารพาณิชย์               34.0            192.0  13000000.0   
43372             ทาวน์โฮม                NaN            191.0   2600000.0   
43373                คอนโด                NaN             45.0   3490000.0   

       ...  count_room_living  count_room_maid  count_room_storage  \
0      ...                NaN              NaN                 NaN   
1      ...                NaN              NaN                 NaN   
2      ...                NaN              NaN                 NaN   
3      ...                NaN              NaN                 NaN   
4      ...                1.0              NaN                 NaN   
...    ...                ...              ...                 ...   
43369  ...                NaN              NaN                 NaN   
43370  ...                NaN              NaN                 NaN   
43371  ...                NaN              NaN                 NaN   
43372  ...                1.0              NaN                 NaN   
43373  ...                1.0              NaN                 NaN   

       count_room_utility         date_created         date_updated  source  \
0                     NaN  2021-11-12 13:22:56  2020-10-14 20:21:01  baania   
1                     NaN  2021-11-12 13:20:17  2020-10-14 00:53:00  baania   
2                     NaN  2022-09-09 15:30:02  2022-09-09 15:03:18  baania   
3                     NaN  2022-03-09 16:30:04  2022-03-09 16:17:44  baania   
4                     NaN  2021-11-12 13:24:53  2020-10-

##Bonus
จังหวัดที่มีอสังหาริมทรัพย์ที่แพงที่สุด เป็นรายจังหวัด 10 จังหวัดแรก

In [43]:
unit_df.groupby('province_en')['price_min'].max().reset_index().sort_values(by='price_min',ascending=False).head(10)

province_en    price_min
2               Bangkok  580000000.0
10            Chon Buri  385000000.0
33           Nonthaburi  185000000.0
45               Phuket  169000000.0
63          Surat Thani  124000000.0
47  Prachuap Khiri Khan   85000000.0
34         Pathum Thani   84000000.0
27    Nakhon Ratchasima   80000000.0
54         Samut Prakan   73000000.0
25        Nakhon Pathom   59000000.0

5 อันดับที่ condo ที่แพงที่สุดรายจังหวัด

In [46]:
unit_df[unit_df['propertytype_name_en'] == 'Condo'].groupby('province_en')['price_min'].max().reset_index().sort_values(by='price_min',ascending=False).head(6)

province_en    price_min
0               Bangkok  580000000.0
6             Chon Buri  200000000.0
27  Prachuap Khiri Khan   85000000.0
25               Phuket   85000000.0
22          Phetchaburi   45000000.0
14    Nakhon Ratchasima   30000000.0

## ลองทำดู

In [45]:
unit_df[unit_df['propertytype_name_en'] == 'Condo'].sort_values(by=['price_min']).iloc[:3,-1]

30708     Samut Prakan
922       Samut Prakan
1652     Nakhon Pathom
Name: province_en, dtype: object