<a href="https://colab.research.google.com/github/Thitiphorn267-3/python_dataviz2023/blob/main/me.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

###Quiz 1
print มาก ที่มี ก 100ตัว

In [17]:
'มา'+('ก' *100)

'มากกกกกกกกกกกกกกกกกกกกกกกกกกกกกกกกกกกกกกกกกกกกกกกกกกกกกกกกกกกกกกกกกกกกกกกกกกกกกกกกกกกกกกกกกกกกกกกกกกกก'

###QUIZ2
กำหนด list เป็นประโยคคำว่า "Department of Statistics, Faculty of Scine, Khon Kaen University, Thailand"

1.ตัดมาเฉพาะคำว่า Faculty of Scine
2.ตัดแบบเว้นทีละ 3 ตัวอักษร
3.ตัดคำว่า Khon Kaen University,Thailand ออกมาแล้วเขียนกลับหลัง

In [1]:
list_Q2='Department of Statitics Faculty of Science, Khonkaen University, Thailand'

In [2]:
list_Q2

'Department of Statitics Faculty of Science, Khonkaen University, Thailand'

In [12]:
list_Q2[24:42] ##1

'Faculty of Science'

In [5]:
list_Q2[::3] ##2

'DamtfticFuyfcn,hknnei,hld'

In [6]:
list_Q2[43::-1]##3

' ,ecneicS fo ytlucaF scititatS fo tnemtrapeD'

###HW1
คำนวณว่าช่วงเวลาต่อไปนี้ ห่างกันกี่ชั่วโมง กี่นาที กี่วินาที (print ออกมาให้สวยงาม)

12:30:15 - 13:41:07
09:11:50 - 21:30:15
19:25:30 - 03:10:15

In [13]:
# 12:30:15 - 13:41:07
q1 = '12:30:15'
Q1 = q1.split(":")
hours1 = int(Q1[0])*3600
minutes1 = int(Q1[1])*60
seconds1 = int(Q1[2])
q2 = '13:41:07'
Q2 = q2.split(":")
hours2 = int(Q2[0])*3600
minutes2 = int(Q2[1])*60
seconds2 = int(Q2[2])
f1 =  hours1 + minutes1 + seconds1
f2 =  hours2 + minutes2 + seconds2
f3 = (f2-f1)
rh = int(f3/3600)
rm = int((f3%3600)/60)
rs = int(f3%60)
print(f' ช่วงเวลาจาก {q1} ถึง {q2} ห่างกัน {rh:,} ชั่วโมง {rm:,} นาที {rs:,} วินาที')

 ช่วงเวลาจาก 12:30:15 ถึง 13:41:07 ห่างกัน 1 ชั่วโมง 10 นาที 52 วินาที


In [14]:
# 09:11:50 - 21:30:15
q1 = '09:11:50'
Q1 = q1.split(":")
hours1 = int(Q1[0])*3600
minutes1 = int(Q1[1])*60
seconds1 = int(Q1[2])
q2 = '21:30:15'
Q2 = q2.split(":")
hours2 = int(Q2[0])*3600
minutes2 = int(Q2[1])*60
seconds2 = int(Q2[2])
f1 =  hours1 + minutes1 + seconds1
f2 =  hours2 + minutes2 + seconds2
f3 = (f2-f1)
rh = int(f3/3600)
rm = int((f3%3600)/60)
rs = int(f3%60)
print(f' ช่วงเวลาจาก {q1} ถึง {q2} ห่างกัน {rh:,} ชั่วโมง {rm:,} นาที {rs:,} วินาที')

 ช่วงเวลาจาก 09:11:50 ถึง 21:30:15 ห่างกัน 12 ชั่วโมง 18 นาที 25 วินาที


In [15]:
### แก้ไข
q5 = '03:10:15'
Q5 = q5.split(":")
hours5 = int(Q5[0])*3600
minutes5 = int(Q5[1])*60
seconds5 = int(Q5[2])
f5 =  hours5 + minutes5 + seconds5
print(f' {q5} แปลงเป็นวินาที ได้ {f5:,} วินาที')

q6 = '19:25:30'
Q6 = q6.split(":")
hours6 = int(Q6[0])*3600
minutes6 = int(Q6[1])*60
seconds6 = int(Q6[2])
f6 =  hours6 + minutes6 + seconds6
print(f' {q6} แปลงเป็นวินาที ได้ {f6:,} วินาที')

f7 = (f5+86400)-f6

hr = int(f7/3600)
mn = int((f7%3600)/60)
s = int(f7%60)
print(f' จาก {q5} ถึง {q6} ห่างกัน {hr:,} ชั่วโมง {mn:,} นาที {s:,} วินาที')

 03:10:15 แปลงเป็นวินาที ได้ 11,415 วินาที
 19:25:30 แปลงเป็นวินาที ได้ 69,930 วินาที
 จาก 03:10:15 ถึง 19:25:30 ห่างกัน 7 ชั่วโมง 44 นาที 45 วินาที


##HW2
สร้าง logo พรรคก้าวไกล

In [7]:
import numpy as np # import เเล้วเปลี่ยนชื่อ จาก numpy เป็น np

In [9]:
ส้ม = np.ones((21,16))
ส้ม[2:5,2:14] = 88
ส้ม[5:7,12:14] = 88
ส้ม[6:8,12:13] = 88
ส้ม[7:9,11:13] = 88
ส้ม[8:10,11:12] = 88
ส้ม[9:10,10:11] = 88
ส้ม[10:11,10:12] = 88
ส้ม[11:12,9:11] = 88
ส้ม[12:13,9:11] = 88
ส้ม[13:14,8:10] = 88
ส้ม[14:15,8:10] = 88
ส้ม[15:16,7:9] = 88
ส้ม[16:17,7:9] = 88
ส้ม[17:18,6:8] = 88
ส้ม[18:19,6:8] = 88

ส้ม[7,3:10] = 88
ส้ม[8,3:9] = 88
ส้ม[9,7:9] = 88
ส้ม[10,6:8] = 88
ส้ม[11,6:8] = 88
ส้ม[12,5:7] = 88
ส้ม[13,5:7] = 88
ส้ม[14,5] = 88

print(ส้ม)

[[ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  1. 88. 88. 88. 88. 88. 88. 88. 88. 88. 88. 88. 88.  1.  1.]
 [ 1.  1. 88. 88. 88. 88. 88. 88. 88. 88. 88. 88. 88. 88.  1.  1.]
 [ 1.  1. 88. 88. 88. 88. 88. 88. 88. 88. 88. 88. 88. 88.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1. 88. 88.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1. 88. 88.  1.  1.]
 [ 1.  1.  1. 88. 88. 88. 88. 88. 88. 88.  1. 88. 88.  1.  1.  1.]
 [ 1.  1.  1. 88. 88. 88. 88. 88. 88.  1.  1. 88. 88.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.  1. 88. 88.  1. 88. 88.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1. 88. 88.  1.  1. 88. 88.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1. 88. 88.  1. 88. 88.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1. 88. 88.  1.  1. 88. 88.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1. 88. 88.  1. 88. 88.  1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1. 88.  1.  1. 88. 88.  1.  1.  1.  1.  1. 

In [10]:
def กก(x):
 ส้ม = x * np.ones((21,16))

 ส้ม[2:5,2:14] = 88
 ส้ม[5:7,12:14] = 88
 ส้ม[6:8,12:13] = 88
 ส้ม[7:9,11:13] = 88
 ส้ม[8:10,11:12] = 88
 ส้ม[9:10,10:11] = 88
 ส้ม[10:11,10:12] = 88
 ส้ม[11:12,9:11] = 88
 ส้ม[12:13,9:11] = 88
 ส้ม[13:14,8:10] = 88
 ส้ม[14:15,8:10] = 88
 ส้ม[15:16,7:9] = 88
 ส้ม[16:17,7:9] = 88
 ส้ม[17:18,6:8] = 88
 ส้ม[18:19,6:8] = 88

 ส้ม[7,3:10] = 88
 ส้ม[8,3:9] = 88
 ส้ม[9,7:9] = 88
 ส้ม[10,6:8] = 88
 ส้ม[11,6:8] = 88
 ส้ม[12,5:7] = 88
 ส้ม[13,5:7] = 88
 ส้ม[14,5] = 88



 print(ส้ม)

In [11]:
กก(7)

[[ 7.  7.  7.  7.  7.  7.  7.  7.  7.  7.  7.  7.  7.  7.  7.  7.]
 [ 7.  7.  7.  7.  7.  7.  7.  7.  7.  7.  7.  7.  7.  7.  7.  7.]
 [ 7.  7. 88. 88. 88. 88. 88. 88. 88. 88. 88. 88. 88. 88.  7.  7.]
 [ 7.  7. 88. 88. 88. 88. 88. 88. 88. 88. 88. 88. 88. 88.  7.  7.]
 [ 7.  7. 88. 88. 88. 88. 88. 88. 88. 88. 88. 88. 88. 88.  7.  7.]
 [ 7.  7.  7.  7.  7.  7.  7.  7.  7.  7.  7.  7. 88. 88.  7.  7.]
 [ 7.  7.  7.  7.  7.  7.  7.  7.  7.  7.  7.  7. 88. 88.  7.  7.]
 [ 7.  7.  7. 88. 88. 88. 88. 88. 88. 88.  7. 88. 88.  7.  7.  7.]
 [ 7.  7.  7. 88. 88. 88. 88. 88. 88.  7.  7. 88. 88.  7.  7.  7.]
 [ 7.  7.  7.  7.  7.  7.  7. 88. 88.  7. 88. 88.  7.  7.  7.  7.]
 [ 7.  7.  7.  7.  7.  7. 88. 88.  7.  7. 88. 88.  7.  7.  7.  7.]
 [ 7.  7.  7.  7.  7.  7. 88. 88.  7. 88. 88.  7.  7.  7.  7.  7.]
 [ 7.  7.  7.  7.  7. 88. 88.  7.  7. 88. 88.  7.  7.  7.  7.  7.]
 [ 7.  7.  7.  7.  7. 88. 88.  7. 88. 88.  7.  7.  7.  7.  7.  7.]
 [ 7.  7.  7.  7.  7. 88.  7.  7. 88. 88.  7.  7.  7.  7.  7. 